steps:

  # ビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--no-cache',
      '--build-arg','NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}',
      '--build-arg','NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}',
      '--build-arg','NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}',
      '--build-arg','NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}',
      '--build-arg','NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}',
      '--build-arg','NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}',
      '--build-arg','NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}',
      '--build-arg','NEXT_PUBLIC_FIREBASE_DATABASE_URL=${_NEXT_PUBLIC_FIREBASE_DATABASE_URL}',
      '--build-arg','NEXT_PUBLIC_BACKEND_URL=${_NEXT_PUBLIC_BACKEND_URL}',
      '-t', '${_REGISTRY}',
      '-f', './frontend/Dockerfile',
      './frontend/'
    ]
    id: Build

  # プッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGISTRY}']
    id: Push

  # デプロイ
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', '${_DEPLOY}',
      '--image', '${_REGISTRY}',
      '--region', 'asia-northeast1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]
    id: Deploy

images:
  - ${_REGISTRY}

substitutions:
  _IMAGE_NAME: 'frontend-docker'
  _DEPLOY: 'frontend-deploy'
  _REGISTRY: 'asia.gcr.io/${PROJECT_ID}/${_IMAGE_NAME}'

options:
  dynamic_substitutions: true # これを追加すると、substitutionsが動的になる
  substitution_option: 'ALLOW_LOOSE'
