import { Stack } from "@mui/material";
import Head from "next/head";

export default function WiseSaying() {
  return (
    <Stack>
      <Head>
        <title>名言DB</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="/Users/dev/my/app/code/Projects/template/frontend/public/favicon.ico"
        />
      </Head>
      名言DB
    </Stack>
  );
}
