# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# 開発環境用
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
version: "3.9"

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: 'STARTUP-TEMPLATE-DB'
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./.db:/var/lib/postgresql/data
    restart: always
